services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: diamovements/foodgram_back:latest
    env_file: .env
    depends_on:
      - db
    restart: always
    volumes:
      - static:/static
      - media:/app/media/
    ports:
      - '8000:8000'

  frontend:
    container_name: foodgram-front
    env_file: .env
    image: diamovements/foodgram_front:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  nginx:
    container_name: foodgram-proxy
    image: diamovements/foodgram_gateway:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/redoc/
      - static:/static
      - media:/media
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media: