name: Пайплайн для Foodgram App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt
    
    - name: Запуск тестов
      env:
        DEBUG: True
        SECRET_KEY: test-secret-key
        ALLOWED_HOSTS: localhost,127.0.0.1
        DB_ENGINE: django.db.backends.postgresql
        DB_NAME: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        DB_HOST: localhost
        DB_PORT: 5432
      run: |
        cd backend
        python manage.py test

  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Установка Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Вход в DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Сборка и отправка образа в DockerHub
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/foodgram:latest